### ISSUE TITLE
Connexion d'un utilisateur

### ISSUE THREAD

**Issue by Munozmu** [Munozmu/TP3-GITHUB-TRAINING#1]
- [x] Choix des technologies
- [x] Sélection du parcours utilisateur de connexion

**Comment by lucastrap** [comment]
![images](https://user-images.githubusercontent.com/95679147/159455425-86b14fc6-a582-48b1-8745-6f13ca0f7ac1.jpg)

**Comment by Hugo-CASTELL** [comment]
![5e57d92cabf3d](https://user-images.githubusercontent.com/100218176/159456184-be1e0f75-57ca-4d0d-b0bf-948e89a4bc28.jpg)

**Comment by lucastrap** [comment]
![download](https://user-images.githubusercontent.com/95679147/159456378-0fc6b1b9-ba27-4f26-967c-b5e73190304e.jpg)

**Comment by Hugo-CASTELL** [comment]
![](https://user-images.githubusercontent.com/95679147/159456378-0fc6b1b9-ba27-4f26-967c-b5e73190304e.jpg) be like

**Comment by lucastrap** [comment]
![69k4jn](https://user-images.githubusercontent.com/95679147/159456653-d183927e-a1b3-4560-9c29-9675be658f78.jpg)
